---
swagger: "2.0"
info:
  version: "v1.0"
  title: "AWS OpenAI Classifier ECO API"
host: "yq1g5tq2pf.execute-api.us-east-1.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /classify:
    get:
      summary: "Подбор классов"
      description: "Для переданного наименования номенклатуры подбирает все классы в глубину на базе классификатора"
      operationId: "classify"
      produces:
      - "application/json"
      parameters:
      - name: "itemName"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/modelResponseForClassifiy"
          example:
            input_item_name: "Труба тип 3-820x9-К52 ГОСТ 20295-85"
            result:
              - class_name: "ТРУБЫ СТАЛЬНЫЕ"
                class_code: "04"
              - class_name: "Трубы стальные круглые(кроме ВГП)"
                class_code: "0401"
              - class_name: "Трубы стальные электросварные"
                class_code: "040102"
              - class_name: "Трубы стальные сварные для магистральных газонефтепроводов"
                class_code: "04010202"
        "400":
          description: "400 response"
        "500":
          description: "500 response"
        "502":
          description: "502 response"
        "504":
          description: "504 response"
      security:
      - api_key: []
  /pickAtt:
    post:
      summary: "Подбор значений для аттрибутов"
      description: "Для переданного наименования номенклатуры на базе переданного конечного класса определяет значения аттрибутов"
      operationId: "pickAtt"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "modelRequestForPickAtt"
        required: true
        schema:
          $ref: "#/definitions/modelRequestForPickAtt"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/modelResponseForPickAtt"
        "400":
          description: "400 response"
        "500":
          description: "500 response"
        "502":
          description: "502 response"
        "504":
          description: "504 response"
      security:
      - api_key: []
  /updateClassifier:
    post:
      summary: "Обновление данных в классификаторе"
      description: "Обновляет данные в классификаторе (Redis). Если ключ уже существует, то данные по нему перезаписываются, если нет — создается новый ключ c переданными по нему данными"
      operationId: "updateClassifier"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "modelRequestUpdateClassifier"
        required: true
        schema:
          $ref: "#/definitions/modelRequestUpdateClassifier"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/modelResponseUpdateClassifier"
        "400":
          description: "400 response"
        "500":
          description: "500 response"
        "502":
          description: "502 response"
        "504":
          description: "504 response"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  modelResponseForPickAtt:
    type: "object"
    properties:
      input_item_name:
        type: "string"
      input_final_class_name:
        type: "string"
      input_final_class_code:
        type: "string"
      result:
        type: "array"
        items:
          type: "object"
          properties:
            attribute_name:
              type: "string"
            attribute_type:
              type: "string"
            attribute_example:
              type: "string"
            attribute_decicion:
              type: "string"
  modelResponseUpdateClassifier:
    type: "object"
    properties:
      result:
        type: "string"
  modelResponseForClassifiy:
    type: "object"
    properties:
      input_item_name:
        type: "string"
      result:
        type: "array"
        items:
          type: "object"
          properties:
            class_name:
              type: "string"
            class_code:
              type: "string"
  modelRequestUpdateClassifier:
    type: "array"
    items:
      type: "object"
      properties:
        key:
          type: "string"
        data:
          type: "object"
          properties:
            code:
              type: "string"
            name:
              type: "string"
            attributes:
              type:
                - "array"
                - null
              items:
                type: "object"
                properties:
                  attribute_name:
                    type: "string"
                  attribute_type:
                    type: "string"
                  attribute_example:
                    type:
                      - "string"
                      - null
                required:
                  - "attribute_name"
                  - "attribute_type"
                  - "attribute_example"
          required:
            - "code"
            - "name"
            - "attributes"
      required:
        - "key"
        - "data"
  modelRequestForPickAtt:
    type: "object"
    required:
    - "final_class_code"
    - "final_class_name"
    - "item_name"
    properties:
      item_name:
        type: "string"
      final_class_name:
        type: "string"
      final_class_code:
        type: "string"
